- name: Add the statsd firewall rules file
  template: >
    src=iptables.j2
    dest=/etc/sysconfig/iptables
    mode=0600
    backup=no
    owner=root
    group=root
  tags:
    - statsd
    - firewall

- name: Reload iptables
  command: /etc/init.d/iptables restart
  tags:
    - statsd
    - firewall
