#####################
# Common
- name: "Make sure the required node version is installed"
  nvm: >
    version={{ statsd_node_version }}
    state=present
    nvm_dir={{ nvm_dir }}
  tags:
    - statsd
    - nodejs

- name: "Create a statsd system user"
  user: >
    name=statsd
    shell=/bin/false
    createhome=no
    state=present
  tags:
    - statsd
    - users

- name: "Download the StatsD repo from GitHub"
  git: >
    repo=https://github.com/etsy/statsd.git
    dest={{ statsd_path }}
    update=yes
    version={{ statsd_version }}
  tags:
    - statsd
    - pkgs

- name: "Install required StatsD backends"
  shell: |
    executable=/bin/bash
    chdir={{ statsd_path }}

    source {{ nvm_dir }}/nvm.sh
    nvm use {{ statsd_node_version }}
    npm install {{ item }}
  with_items:
    - statsd-librato-backend
    - statsd-instrumental-backend
    - statsd-ducksboard-backend
    - js-yaml
  tags:
    - statsd
    - pkgs

- name: "Install statsd init.d script"
  template: >
    src=statsd.init.sh.j2
    dest=/etc/init.d/statsd
    owner=statsd
    group=statsd
    mode=0700
  notify:
    - Restart StatsD
  tags:
    - statsd
    - files

- name: "Make sure /etc/statsd exists"
  file: >
    path=/etc/statsd
    state=directory
    owner=statsd
    group=statsd
    mode=0700
  tags:
    - statsd
    - files
    - configs

- name: "Install StatsD config file"
  template: >
    src=config.js.j2
    dest=/etc/statsd/config.js
    owner=statsd
    group=statsd
    mode=0600
  tags:
    - statsd
    - files
    - configs
  notify:
    - Restart StatsD

- name: "Set StatsD runlevel and ensure its running"
  service: >
    name=statsd
    state=running
    enabled=yes
    runlevel=5
  tags:
    - statsd
